CREATE TABLE User (
  ID_USER   INT NOT NULL AUTO_INCREMENT,
  PSEUDO    VARCHAR(25),
  FIRSTNAME VARCHAR(50),
  LASTNAME  VARCHAR(25),
  PASSWORD  VARCHAR(50),
  EMAIL     VARCHAR(100),
  PRIMARY KEY (ID_USER)
)
  ENGINE = INNODB;


CREATE TABLE TEST (
  ID_USER   INT NOT NULL,
  PSEUDO    VARCHAR(25),
  PRIMARY KEY (ID_USER)
)
  ENGINE = INNODB;

insert into TEST VALUES (1, 'lili' );